name: somethin somethin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#343d22'
    - '#677230'
    - '#da91e2'
    - '#e9da63'
  brandStrength: 0.5625
  lightness: 0.3622524074744433
  saturation: 0.4989167081657797
  rhythmicContrast: 0.8045112874824554
purpose: []
