name: somethin somethin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e69881'
    - '#ce6200'
    - '#426f39'
    - '#8f150c'
  brandStrength: 0.625
  lightness: 0.3622524074744433
  saturation: 0.25
  rhythmicContrast: 0.8045112874824554
purpose: []
