name: somethin somethin
favicon: null
layout_spectrum: 0.52346
typography_spectrum: 0.54554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25b3c5'
    - '#ccad87'
    - '#f35988'
    - '#68409a'
    - '#14016d'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
